import { Karla } from "next/font/google";
import "./globals.css";

// Import Karla font
const karla = Karla({
  variable: "--font-karla",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="black">
      <body className={`${karla.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
